// GENERATED by android/tools/gen_vk_loader.py -- do not edit by hand.
// See that script for why this shim exists.
#include "stdafx.h"

#ifdef __ANDROID__

#include "vk_android_loader.h"
#include "util/logs.hpp"

#include <dlfcn.h>
#include <mutex>
#include <string>

LOG_CHANNEL(vk_loader);

extern "C"
{
	PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR = nullptr;
	PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers = nullptr;
	PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets = nullptr;
	PFN_vkAllocateMemory vkAllocateMemory = nullptr;
	PFN_vkBeginCommandBuffer vkBeginCommandBuffer = nullptr;
	PFN_vkBindBufferMemory vkBindBufferMemory = nullptr;
	PFN_vkBindBufferMemory2 vkBindBufferMemory2 = nullptr;
	PFN_vkBindImageMemory vkBindImageMemory = nullptr;
	PFN_vkBindImageMemory2 vkBindImageMemory2 = nullptr;
	PFN_vkCmdBeginQuery vkCmdBeginQuery = nullptr;
	PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass = nullptr;
	PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets = nullptr;
	PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer = nullptr;
	PFN_vkCmdBindPipeline vkCmdBindPipeline = nullptr;
	PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers = nullptr;
	PFN_vkCmdBlitImage vkCmdBlitImage = nullptr;
	PFN_vkCmdClearAttachments vkCmdClearAttachments = nullptr;
	PFN_vkCmdClearColorImage vkCmdClearColorImage = nullptr;
	PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage = nullptr;
	PFN_vkCmdCopyBuffer vkCmdCopyBuffer = nullptr;
	PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage = nullptr;
	PFN_vkCmdCopyImage vkCmdCopyImage = nullptr;
	PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer = nullptr;
	PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults = nullptr;
	PFN_vkCmdDispatch vkCmdDispatch = nullptr;
	PFN_vkCmdDraw vkCmdDraw = nullptr;
	PFN_vkCmdDrawIndexed vkCmdDrawIndexed = nullptr;
	PFN_vkCmdEndQuery vkCmdEndQuery = nullptr;
	PFN_vkCmdEndRenderPass vkCmdEndRenderPass = nullptr;
	PFN_vkCmdFillBuffer vkCmdFillBuffer = nullptr;
	PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier = nullptr;
	PFN_vkCmdPushConstants vkCmdPushConstants = nullptr;
	PFN_vkCmdResetQueryPool vkCmdResetQueryPool = nullptr;
	PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants = nullptr;
	PFN_vkCmdSetDepthBias vkCmdSetDepthBias = nullptr;
	PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds = nullptr;
	PFN_vkCmdSetEvent vkCmdSetEvent = nullptr;
	PFN_vkCmdSetLineWidth vkCmdSetLineWidth = nullptr;
	PFN_vkCmdSetScissor vkCmdSetScissor = nullptr;
	PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask = nullptr;
	PFN_vkCmdSetStencilReference vkCmdSetStencilReference = nullptr;
	PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask = nullptr;
	PFN_vkCmdSetViewport vkCmdSetViewport = nullptr;
	PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer = nullptr;
	PFN_vkCmdWaitEvents vkCmdWaitEvents = nullptr;
	PFN_vkCreateAndroidSurfaceKHR vkCreateAndroidSurfaceKHR = nullptr;
	PFN_vkCreateBuffer vkCreateBuffer = nullptr;
	PFN_vkCreateBufferView vkCreateBufferView = nullptr;
	PFN_vkCreateCommandPool vkCreateCommandPool = nullptr;
	PFN_vkCreateComputePipelines vkCreateComputePipelines = nullptr;
	PFN_vkCreateDescriptorPool vkCreateDescriptorPool = nullptr;
	PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout = nullptr;
	PFN_vkCreateDevice vkCreateDevice = nullptr;
	PFN_vkCreateEvent vkCreateEvent = nullptr;
	PFN_vkCreateFence vkCreateFence = nullptr;
	PFN_vkCreateFramebuffer vkCreateFramebuffer = nullptr;
	PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines = nullptr;
	PFN_vkCreateImage vkCreateImage = nullptr;
	PFN_vkCreateImageView vkCreateImageView = nullptr;
	PFN_vkCreateInstance vkCreateInstance = nullptr;
	PFN_vkCreatePipelineCache vkCreatePipelineCache = nullptr;
	PFN_vkCreatePipelineLayout vkCreatePipelineLayout = nullptr;
	PFN_vkCreateQueryPool vkCreateQueryPool = nullptr;
	PFN_vkCreateRenderPass vkCreateRenderPass = nullptr;
	PFN_vkCreateSampler vkCreateSampler = nullptr;
	PFN_vkCreateSemaphore vkCreateSemaphore = nullptr;
	PFN_vkCreateShaderModule vkCreateShaderModule = nullptr;
	PFN_vkDestroyBuffer vkDestroyBuffer = nullptr;
	PFN_vkDestroyBufferView vkDestroyBufferView = nullptr;
	PFN_vkDestroyCommandPool vkDestroyCommandPool = nullptr;
	PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool = nullptr;
	PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout = nullptr;
	PFN_vkDestroyDevice vkDestroyDevice = nullptr;
	PFN_vkDestroyEvent vkDestroyEvent = nullptr;
	PFN_vkDestroyFence vkDestroyFence = nullptr;
	PFN_vkDestroyFramebuffer vkDestroyFramebuffer = nullptr;
	PFN_vkDestroyImage vkDestroyImage = nullptr;
	PFN_vkDestroyImageView vkDestroyImageView = nullptr;
	PFN_vkDestroyInstance vkDestroyInstance = nullptr;
	PFN_vkDestroyPipeline vkDestroyPipeline = nullptr;
	PFN_vkDestroyPipelineCache vkDestroyPipelineCache = nullptr;
	PFN_vkGetPipelineCacheData vkGetPipelineCacheData = nullptr;
	PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout = nullptr;
	PFN_vkDestroyQueryPool vkDestroyQueryPool = nullptr;
	PFN_vkDestroyRenderPass vkDestroyRenderPass = nullptr;
	PFN_vkDestroySampler vkDestroySampler = nullptr;
	PFN_vkDestroySemaphore vkDestroySemaphore = nullptr;
	PFN_vkDestroyShaderModule vkDestroyShaderModule = nullptr;
	PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR = nullptr;
	PFN_vkDeviceWaitIdle vkDeviceWaitIdle = nullptr;
	PFN_vkEndCommandBuffer vkEndCommandBuffer = nullptr;
	PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties = nullptr;
	PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties = nullptr;
	PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices = nullptr;
	PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges = nullptr;
	PFN_vkFreeCommandBuffers vkFreeCommandBuffers = nullptr;
	PFN_vkFreeMemory vkFreeMemory = nullptr;
	PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements = nullptr;
	PFN_vkGetBufferMemoryRequirements2 vkGetBufferMemoryRequirements2 = nullptr;
	PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr = nullptr;
	PFN_vkGetDeviceQueue vkGetDeviceQueue = nullptr;
	PFN_vkGetEventStatus vkGetEventStatus = nullptr;
	PFN_vkGetFenceStatus vkGetFenceStatus = nullptr;
	PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements = nullptr;
	PFN_vkGetImageMemoryRequirements2 vkGetImageMemoryRequirements2 = nullptr;
	PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout = nullptr;
	PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = nullptr;
	PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures = nullptr;
	PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2 = nullptr;
	PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties = nullptr;
	PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties = nullptr;
	PFN_vkGetPhysicalDeviceMemoryProperties2 vkGetPhysicalDeviceMemoryProperties2 = nullptr;
	PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties = nullptr;
	PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2 = nullptr;
	PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties = nullptr;
	PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR = nullptr;
	PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR = nullptr;
	PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR = nullptr;
	PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR = nullptr;
	PFN_vkGetQueryPoolResults vkGetQueryPoolResults = nullptr;
	PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp = nullptr;
	PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges = nullptr;
	PFN_vkMapMemory vkMapMemory = nullptr;
	PFN_vkQueueSubmit vkQueueSubmit = nullptr;
	PFN_vkResetCommandBuffer vkResetCommandBuffer = nullptr;
	PFN_vkResetDescriptorPool vkResetDescriptorPool = nullptr;
	PFN_vkResetEvent vkResetEvent = nullptr;
	PFN_vkResetFences vkResetFences = nullptr;
	PFN_vkSetEvent vkSetEvent = nullptr;
	PFN_vkUnmapMemory vkUnmapMemory = nullptr;
	PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets = nullptr;
	PFN_vkWaitForFences vkWaitForFences = nullptr;
}

namespace vk::android
{
	namespace
	{
		std::mutex g_mutex;
		void* g_handle = nullptr;
		bool g_custom = false;
		std::string g_error;

		// Resolve every entry point from `handle`.
		//
		// vkGetInstanceProcAddr comes from dlsym; everything else goes through IT
		// rather than dlsym, because a custom or layered driver may only expose
		// the rest via its loader entry point.
		//
		// Instance-level functions cannot resolve against a null instance, so they
		// stay null here and are filled in by resolve_instance() once the
		// VkInstance exists. dlsym is the fallback for both.
		bool resolve_all(void* handle)
		{
			vkGetInstanceProcAddr = reinterpret_cast<PFN_vkGetInstanceProcAddr>(
				dlsym(handle, "vkGetInstanceProcAddr"));

			if (!vkGetInstanceProcAddr)
			{
				g_error = "driver exports no vkGetInstanceProcAddr";
				return false;
			}

			vkAcquireNextImageKHR = reinterpret_cast<PFN_vkAcquireNextImageKHR>(vkGetInstanceProcAddr(nullptr, "vkAcquireNextImageKHR"));
			if (!vkAcquireNextImageKHR) vkAcquireNextImageKHR = reinterpret_cast<PFN_vkAcquireNextImageKHR>(dlsym(handle, "vkAcquireNextImageKHR"));
			vkAllocateCommandBuffers = reinterpret_cast<PFN_vkAllocateCommandBuffers>(vkGetInstanceProcAddr(nullptr, "vkAllocateCommandBuffers"));
			if (!vkAllocateCommandBuffers) vkAllocateCommandBuffers = reinterpret_cast<PFN_vkAllocateCommandBuffers>(dlsym(handle, "vkAllocateCommandBuffers"));
			vkAllocateDescriptorSets = reinterpret_cast<PFN_vkAllocateDescriptorSets>(vkGetInstanceProcAddr(nullptr, "vkAllocateDescriptorSets"));
			if (!vkAllocateDescriptorSets) vkAllocateDescriptorSets = reinterpret_cast<PFN_vkAllocateDescriptorSets>(dlsym(handle, "vkAllocateDescriptorSets"));
			vkAllocateMemory = reinterpret_cast<PFN_vkAllocateMemory>(vkGetInstanceProcAddr(nullptr, "vkAllocateMemory"));
			if (!vkAllocateMemory) vkAllocateMemory = reinterpret_cast<PFN_vkAllocateMemory>(dlsym(handle, "vkAllocateMemory"));
			vkBeginCommandBuffer = reinterpret_cast<PFN_vkBeginCommandBuffer>(vkGetInstanceProcAddr(nullptr, "vkBeginCommandBuffer"));
			if (!vkBeginCommandBuffer) vkBeginCommandBuffer = reinterpret_cast<PFN_vkBeginCommandBuffer>(dlsym(handle, "vkBeginCommandBuffer"));
			vkBindBufferMemory = reinterpret_cast<PFN_vkBindBufferMemory>(vkGetInstanceProcAddr(nullptr, "vkBindBufferMemory"));
			if (!vkBindBufferMemory) vkBindBufferMemory = reinterpret_cast<PFN_vkBindBufferMemory>(dlsym(handle, "vkBindBufferMemory"));
			vkBindBufferMemory2 = reinterpret_cast<PFN_vkBindBufferMemory2>(vkGetInstanceProcAddr(nullptr, "vkBindBufferMemory2"));
			if (!vkBindBufferMemory2) vkBindBufferMemory2 = reinterpret_cast<PFN_vkBindBufferMemory2>(dlsym(handle, "vkBindBufferMemory2"));
			vkBindImageMemory = reinterpret_cast<PFN_vkBindImageMemory>(vkGetInstanceProcAddr(nullptr, "vkBindImageMemory"));
			if (!vkBindImageMemory) vkBindImageMemory = reinterpret_cast<PFN_vkBindImageMemory>(dlsym(handle, "vkBindImageMemory"));
			vkBindImageMemory2 = reinterpret_cast<PFN_vkBindImageMemory2>(vkGetInstanceProcAddr(nullptr, "vkBindImageMemory2"));
			if (!vkBindImageMemory2) vkBindImageMemory2 = reinterpret_cast<PFN_vkBindImageMemory2>(dlsym(handle, "vkBindImageMemory2"));
			vkCmdBeginQuery = reinterpret_cast<PFN_vkCmdBeginQuery>(vkGetInstanceProcAddr(nullptr, "vkCmdBeginQuery"));
			if (!vkCmdBeginQuery) vkCmdBeginQuery = reinterpret_cast<PFN_vkCmdBeginQuery>(dlsym(handle, "vkCmdBeginQuery"));
			vkCmdBeginRenderPass = reinterpret_cast<PFN_vkCmdBeginRenderPass>(vkGetInstanceProcAddr(nullptr, "vkCmdBeginRenderPass"));
			if (!vkCmdBeginRenderPass) vkCmdBeginRenderPass = reinterpret_cast<PFN_vkCmdBeginRenderPass>(dlsym(handle, "vkCmdBeginRenderPass"));
			vkCmdBindDescriptorSets = reinterpret_cast<PFN_vkCmdBindDescriptorSets>(vkGetInstanceProcAddr(nullptr, "vkCmdBindDescriptorSets"));
			if (!vkCmdBindDescriptorSets) vkCmdBindDescriptorSets = reinterpret_cast<PFN_vkCmdBindDescriptorSets>(dlsym(handle, "vkCmdBindDescriptorSets"));
			vkCmdBindIndexBuffer = reinterpret_cast<PFN_vkCmdBindIndexBuffer>(vkGetInstanceProcAddr(nullptr, "vkCmdBindIndexBuffer"));
			if (!vkCmdBindIndexBuffer) vkCmdBindIndexBuffer = reinterpret_cast<PFN_vkCmdBindIndexBuffer>(dlsym(handle, "vkCmdBindIndexBuffer"));
			vkCmdBindPipeline = reinterpret_cast<PFN_vkCmdBindPipeline>(vkGetInstanceProcAddr(nullptr, "vkCmdBindPipeline"));
			if (!vkCmdBindPipeline) vkCmdBindPipeline = reinterpret_cast<PFN_vkCmdBindPipeline>(dlsym(handle, "vkCmdBindPipeline"));
			vkCmdBindVertexBuffers = reinterpret_cast<PFN_vkCmdBindVertexBuffers>(vkGetInstanceProcAddr(nullptr, "vkCmdBindVertexBuffers"));
			if (!vkCmdBindVertexBuffers) vkCmdBindVertexBuffers = reinterpret_cast<PFN_vkCmdBindVertexBuffers>(dlsym(handle, "vkCmdBindVertexBuffers"));
			vkCmdBlitImage = reinterpret_cast<PFN_vkCmdBlitImage>(vkGetInstanceProcAddr(nullptr, "vkCmdBlitImage"));
			if (!vkCmdBlitImage) vkCmdBlitImage = reinterpret_cast<PFN_vkCmdBlitImage>(dlsym(handle, "vkCmdBlitImage"));
			vkCmdClearAttachments = reinterpret_cast<PFN_vkCmdClearAttachments>(vkGetInstanceProcAddr(nullptr, "vkCmdClearAttachments"));
			if (!vkCmdClearAttachments) vkCmdClearAttachments = reinterpret_cast<PFN_vkCmdClearAttachments>(dlsym(handle, "vkCmdClearAttachments"));
			vkCmdClearColorImage = reinterpret_cast<PFN_vkCmdClearColorImage>(vkGetInstanceProcAddr(nullptr, "vkCmdClearColorImage"));
			if (!vkCmdClearColorImage) vkCmdClearColorImage = reinterpret_cast<PFN_vkCmdClearColorImage>(dlsym(handle, "vkCmdClearColorImage"));
			vkCmdClearDepthStencilImage = reinterpret_cast<PFN_vkCmdClearDepthStencilImage>(vkGetInstanceProcAddr(nullptr, "vkCmdClearDepthStencilImage"));
			if (!vkCmdClearDepthStencilImage) vkCmdClearDepthStencilImage = reinterpret_cast<PFN_vkCmdClearDepthStencilImage>(dlsym(handle, "vkCmdClearDepthStencilImage"));
			vkCmdCopyBuffer = reinterpret_cast<PFN_vkCmdCopyBuffer>(vkGetInstanceProcAddr(nullptr, "vkCmdCopyBuffer"));
			if (!vkCmdCopyBuffer) vkCmdCopyBuffer = reinterpret_cast<PFN_vkCmdCopyBuffer>(dlsym(handle, "vkCmdCopyBuffer"));
			vkCmdCopyBufferToImage = reinterpret_cast<PFN_vkCmdCopyBufferToImage>(vkGetInstanceProcAddr(nullptr, "vkCmdCopyBufferToImage"));
			if (!vkCmdCopyBufferToImage) vkCmdCopyBufferToImage = reinterpret_cast<PFN_vkCmdCopyBufferToImage>(dlsym(handle, "vkCmdCopyBufferToImage"));
			vkCmdCopyImage = reinterpret_cast<PFN_vkCmdCopyImage>(vkGetInstanceProcAddr(nullptr, "vkCmdCopyImage"));
			if (!vkCmdCopyImage) vkCmdCopyImage = reinterpret_cast<PFN_vkCmdCopyImage>(dlsym(handle, "vkCmdCopyImage"));
			vkCmdCopyImageToBuffer = reinterpret_cast<PFN_vkCmdCopyImageToBuffer>(vkGetInstanceProcAddr(nullptr, "vkCmdCopyImageToBuffer"));
			if (!vkCmdCopyImageToBuffer) vkCmdCopyImageToBuffer = reinterpret_cast<PFN_vkCmdCopyImageToBuffer>(dlsym(handle, "vkCmdCopyImageToBuffer"));
			vkCmdCopyQueryPoolResults = reinterpret_cast<PFN_vkCmdCopyQueryPoolResults>(vkGetInstanceProcAddr(nullptr, "vkCmdCopyQueryPoolResults"));
			if (!vkCmdCopyQueryPoolResults) vkCmdCopyQueryPoolResults = reinterpret_cast<PFN_vkCmdCopyQueryPoolResults>(dlsym(handle, "vkCmdCopyQueryPoolResults"));
			vkCmdDispatch = reinterpret_cast<PFN_vkCmdDispatch>(vkGetInstanceProcAddr(nullptr, "vkCmdDispatch"));
			if (!vkCmdDispatch) vkCmdDispatch = reinterpret_cast<PFN_vkCmdDispatch>(dlsym(handle, "vkCmdDispatch"));
			vkCmdDraw = reinterpret_cast<PFN_vkCmdDraw>(vkGetInstanceProcAddr(nullptr, "vkCmdDraw"));
			if (!vkCmdDraw) vkCmdDraw = reinterpret_cast<PFN_vkCmdDraw>(dlsym(handle, "vkCmdDraw"));
			vkCmdDrawIndexed = reinterpret_cast<PFN_vkCmdDrawIndexed>(vkGetInstanceProcAddr(nullptr, "vkCmdDrawIndexed"));
			if (!vkCmdDrawIndexed) vkCmdDrawIndexed = reinterpret_cast<PFN_vkCmdDrawIndexed>(dlsym(handle, "vkCmdDrawIndexed"));
			vkCmdEndQuery = reinterpret_cast<PFN_vkCmdEndQuery>(vkGetInstanceProcAddr(nullptr, "vkCmdEndQuery"));
			if (!vkCmdEndQuery) vkCmdEndQuery = reinterpret_cast<PFN_vkCmdEndQuery>(dlsym(handle, "vkCmdEndQuery"));
			vkCmdEndRenderPass = reinterpret_cast<PFN_vkCmdEndRenderPass>(vkGetInstanceProcAddr(nullptr, "vkCmdEndRenderPass"));
			if (!vkCmdEndRenderPass) vkCmdEndRenderPass = reinterpret_cast<PFN_vkCmdEndRenderPass>(dlsym(handle, "vkCmdEndRenderPass"));
			vkCmdFillBuffer = reinterpret_cast<PFN_vkCmdFillBuffer>(vkGetInstanceProcAddr(nullptr, "vkCmdFillBuffer"));
			if (!vkCmdFillBuffer) vkCmdFillBuffer = reinterpret_cast<PFN_vkCmdFillBuffer>(dlsym(handle, "vkCmdFillBuffer"));
			vkCmdPipelineBarrier = reinterpret_cast<PFN_vkCmdPipelineBarrier>(vkGetInstanceProcAddr(nullptr, "vkCmdPipelineBarrier"));
			if (!vkCmdPipelineBarrier) vkCmdPipelineBarrier = reinterpret_cast<PFN_vkCmdPipelineBarrier>(dlsym(handle, "vkCmdPipelineBarrier"));
			vkCmdPushConstants = reinterpret_cast<PFN_vkCmdPushConstants>(vkGetInstanceProcAddr(nullptr, "vkCmdPushConstants"));
			if (!vkCmdPushConstants) vkCmdPushConstants = reinterpret_cast<PFN_vkCmdPushConstants>(dlsym(handle, "vkCmdPushConstants"));
			vkCmdResetQueryPool = reinterpret_cast<PFN_vkCmdResetQueryPool>(vkGetInstanceProcAddr(nullptr, "vkCmdResetQueryPool"));
			if (!vkCmdResetQueryPool) vkCmdResetQueryPool = reinterpret_cast<PFN_vkCmdResetQueryPool>(dlsym(handle, "vkCmdResetQueryPool"));
			vkCmdSetBlendConstants = reinterpret_cast<PFN_vkCmdSetBlendConstants>(vkGetInstanceProcAddr(nullptr, "vkCmdSetBlendConstants"));
			if (!vkCmdSetBlendConstants) vkCmdSetBlendConstants = reinterpret_cast<PFN_vkCmdSetBlendConstants>(dlsym(handle, "vkCmdSetBlendConstants"));
			vkCmdSetDepthBias = reinterpret_cast<PFN_vkCmdSetDepthBias>(vkGetInstanceProcAddr(nullptr, "vkCmdSetDepthBias"));
			if (!vkCmdSetDepthBias) vkCmdSetDepthBias = reinterpret_cast<PFN_vkCmdSetDepthBias>(dlsym(handle, "vkCmdSetDepthBias"));
			vkCmdSetDepthBounds = reinterpret_cast<PFN_vkCmdSetDepthBounds>(vkGetInstanceProcAddr(nullptr, "vkCmdSetDepthBounds"));
			if (!vkCmdSetDepthBounds) vkCmdSetDepthBounds = reinterpret_cast<PFN_vkCmdSetDepthBounds>(dlsym(handle, "vkCmdSetDepthBounds"));
			vkCmdSetEvent = reinterpret_cast<PFN_vkCmdSetEvent>(vkGetInstanceProcAddr(nullptr, "vkCmdSetEvent"));
			if (!vkCmdSetEvent) vkCmdSetEvent = reinterpret_cast<PFN_vkCmdSetEvent>(dlsym(handle, "vkCmdSetEvent"));
			vkCmdSetLineWidth = reinterpret_cast<PFN_vkCmdSetLineWidth>(vkGetInstanceProcAddr(nullptr, "vkCmdSetLineWidth"));
			if (!vkCmdSetLineWidth) vkCmdSetLineWidth = reinterpret_cast<PFN_vkCmdSetLineWidth>(dlsym(handle, "vkCmdSetLineWidth"));
			vkCmdSetScissor = reinterpret_cast<PFN_vkCmdSetScissor>(vkGetInstanceProcAddr(nullptr, "vkCmdSetScissor"));
			if (!vkCmdSetScissor) vkCmdSetScissor = reinterpret_cast<PFN_vkCmdSetScissor>(dlsym(handle, "vkCmdSetScissor"));
			vkCmdSetStencilCompareMask = reinterpret_cast<PFN_vkCmdSetStencilCompareMask>(vkGetInstanceProcAddr(nullptr, "vkCmdSetStencilCompareMask"));
			if (!vkCmdSetStencilCompareMask) vkCmdSetStencilCompareMask = reinterpret_cast<PFN_vkCmdSetStencilCompareMask>(dlsym(handle, "vkCmdSetStencilCompareMask"));
			vkCmdSetStencilReference = reinterpret_cast<PFN_vkCmdSetStencilReference>(vkGetInstanceProcAddr(nullptr, "vkCmdSetStencilReference"));
			if (!vkCmdSetStencilReference) vkCmdSetStencilReference = reinterpret_cast<PFN_vkCmdSetStencilReference>(dlsym(handle, "vkCmdSetStencilReference"));
			vkCmdSetStencilWriteMask = reinterpret_cast<PFN_vkCmdSetStencilWriteMask>(vkGetInstanceProcAddr(nullptr, "vkCmdSetStencilWriteMask"));
			if (!vkCmdSetStencilWriteMask) vkCmdSetStencilWriteMask = reinterpret_cast<PFN_vkCmdSetStencilWriteMask>(dlsym(handle, "vkCmdSetStencilWriteMask"));
			vkCmdSetViewport = reinterpret_cast<PFN_vkCmdSetViewport>(vkGetInstanceProcAddr(nullptr, "vkCmdSetViewport"));
			if (!vkCmdSetViewport) vkCmdSetViewport = reinterpret_cast<PFN_vkCmdSetViewport>(dlsym(handle, "vkCmdSetViewport"));
			vkCmdUpdateBuffer = reinterpret_cast<PFN_vkCmdUpdateBuffer>(vkGetInstanceProcAddr(nullptr, "vkCmdUpdateBuffer"));
			if (!vkCmdUpdateBuffer) vkCmdUpdateBuffer = reinterpret_cast<PFN_vkCmdUpdateBuffer>(dlsym(handle, "vkCmdUpdateBuffer"));
			vkCmdWaitEvents = reinterpret_cast<PFN_vkCmdWaitEvents>(vkGetInstanceProcAddr(nullptr, "vkCmdWaitEvents"));
			if (!vkCmdWaitEvents) vkCmdWaitEvents = reinterpret_cast<PFN_vkCmdWaitEvents>(dlsym(handle, "vkCmdWaitEvents"));
			vkCreateAndroidSurfaceKHR = reinterpret_cast<PFN_vkCreateAndroidSurfaceKHR>(vkGetInstanceProcAddr(nullptr, "vkCreateAndroidSurfaceKHR"));
			if (!vkCreateAndroidSurfaceKHR) vkCreateAndroidSurfaceKHR = reinterpret_cast<PFN_vkCreateAndroidSurfaceKHR>(dlsym(handle, "vkCreateAndroidSurfaceKHR"));
			vkCreateBuffer = reinterpret_cast<PFN_vkCreateBuffer>(vkGetInstanceProcAddr(nullptr, "vkCreateBuffer"));
			if (!vkCreateBuffer) vkCreateBuffer = reinterpret_cast<PFN_vkCreateBuffer>(dlsym(handle, "vkCreateBuffer"));
			vkCreateBufferView = reinterpret_cast<PFN_vkCreateBufferView>(vkGetInstanceProcAddr(nullptr, "vkCreateBufferView"));
			if (!vkCreateBufferView) vkCreateBufferView = reinterpret_cast<PFN_vkCreateBufferView>(dlsym(handle, "vkCreateBufferView"));
			vkCreateCommandPool = reinterpret_cast<PFN_vkCreateCommandPool>(vkGetInstanceProcAddr(nullptr, "vkCreateCommandPool"));
			if (!vkCreateCommandPool) vkCreateCommandPool = reinterpret_cast<PFN_vkCreateCommandPool>(dlsym(handle, "vkCreateCommandPool"));
			vkCreateComputePipelines = reinterpret_cast<PFN_vkCreateComputePipelines>(vkGetInstanceProcAddr(nullptr, "vkCreateComputePipelines"));
			if (!vkCreateComputePipelines) vkCreateComputePipelines = reinterpret_cast<PFN_vkCreateComputePipelines>(dlsym(handle, "vkCreateComputePipelines"));
			vkCreateDescriptorPool = reinterpret_cast<PFN_vkCreateDescriptorPool>(vkGetInstanceProcAddr(nullptr, "vkCreateDescriptorPool"));
			if (!vkCreateDescriptorPool) vkCreateDescriptorPool = reinterpret_cast<PFN_vkCreateDescriptorPool>(dlsym(handle, "vkCreateDescriptorPool"));
			vkCreateDescriptorSetLayout = reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(vkGetInstanceProcAddr(nullptr, "vkCreateDescriptorSetLayout"));
			if (!vkCreateDescriptorSetLayout) vkCreateDescriptorSetLayout = reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(dlsym(handle, "vkCreateDescriptorSetLayout"));
			vkCreateDevice = reinterpret_cast<PFN_vkCreateDevice>(vkGetInstanceProcAddr(nullptr, "vkCreateDevice"));
			if (!vkCreateDevice) vkCreateDevice = reinterpret_cast<PFN_vkCreateDevice>(dlsym(handle, "vkCreateDevice"));
			vkCreateEvent = reinterpret_cast<PFN_vkCreateEvent>(vkGetInstanceProcAddr(nullptr, "vkCreateEvent"));
			if (!vkCreateEvent) vkCreateEvent = reinterpret_cast<PFN_vkCreateEvent>(dlsym(handle, "vkCreateEvent"));
			vkCreateFence = reinterpret_cast<PFN_vkCreateFence>(vkGetInstanceProcAddr(nullptr, "vkCreateFence"));
			if (!vkCreateFence) vkCreateFence = reinterpret_cast<PFN_vkCreateFence>(dlsym(handle, "vkCreateFence"));
			vkCreateFramebuffer = reinterpret_cast<PFN_vkCreateFramebuffer>(vkGetInstanceProcAddr(nullptr, "vkCreateFramebuffer"));
			if (!vkCreateFramebuffer) vkCreateFramebuffer = reinterpret_cast<PFN_vkCreateFramebuffer>(dlsym(handle, "vkCreateFramebuffer"));
			vkCreateGraphicsPipelines = reinterpret_cast<PFN_vkCreateGraphicsPipelines>(vkGetInstanceProcAddr(nullptr, "vkCreateGraphicsPipelines"));
			if (!vkCreateGraphicsPipelines) vkCreateGraphicsPipelines = reinterpret_cast<PFN_vkCreateGraphicsPipelines>(dlsym(handle, "vkCreateGraphicsPipelines"));
			vkCreateImage = reinterpret_cast<PFN_vkCreateImage>(vkGetInstanceProcAddr(nullptr, "vkCreateImage"));
			if (!vkCreateImage) vkCreateImage = reinterpret_cast<PFN_vkCreateImage>(dlsym(handle, "vkCreateImage"));
			vkCreateImageView = reinterpret_cast<PFN_vkCreateImageView>(vkGetInstanceProcAddr(nullptr, "vkCreateImageView"));
			if (!vkCreateImageView) vkCreateImageView = reinterpret_cast<PFN_vkCreateImageView>(dlsym(handle, "vkCreateImageView"));
			vkCreateInstance = reinterpret_cast<PFN_vkCreateInstance>(vkGetInstanceProcAddr(nullptr, "vkCreateInstance"));
			if (!vkCreateInstance) vkCreateInstance = reinterpret_cast<PFN_vkCreateInstance>(dlsym(handle, "vkCreateInstance"));
			vkCreatePipelineCache = reinterpret_cast<PFN_vkCreatePipelineCache>(vkGetInstanceProcAddr(nullptr, "vkCreatePipelineCache"));
			if (!vkCreatePipelineCache) vkCreatePipelineCache = reinterpret_cast<PFN_vkCreatePipelineCache>(dlsym(handle, "vkCreatePipelineCache"));
			vkCreatePipelineLayout = reinterpret_cast<PFN_vkCreatePipelineLayout>(vkGetInstanceProcAddr(nullptr, "vkCreatePipelineLayout"));
			if (!vkCreatePipelineLayout) vkCreatePipelineLayout = reinterpret_cast<PFN_vkCreatePipelineLayout>(dlsym(handle, "vkCreatePipelineLayout"));
			vkCreateQueryPool = reinterpret_cast<PFN_vkCreateQueryPool>(vkGetInstanceProcAddr(nullptr, "vkCreateQueryPool"));
			if (!vkCreateQueryPool) vkCreateQueryPool = reinterpret_cast<PFN_vkCreateQueryPool>(dlsym(handle, "vkCreateQueryPool"));
			vkCreateRenderPass = reinterpret_cast<PFN_vkCreateRenderPass>(vkGetInstanceProcAddr(nullptr, "vkCreateRenderPass"));
			if (!vkCreateRenderPass) vkCreateRenderPass = reinterpret_cast<PFN_vkCreateRenderPass>(dlsym(handle, "vkCreateRenderPass"));
			vkCreateSampler = reinterpret_cast<PFN_vkCreateSampler>(vkGetInstanceProcAddr(nullptr, "vkCreateSampler"));
			if (!vkCreateSampler) vkCreateSampler = reinterpret_cast<PFN_vkCreateSampler>(dlsym(handle, "vkCreateSampler"));
			vkCreateSemaphore = reinterpret_cast<PFN_vkCreateSemaphore>(vkGetInstanceProcAddr(nullptr, "vkCreateSemaphore"));
			if (!vkCreateSemaphore) vkCreateSemaphore = reinterpret_cast<PFN_vkCreateSemaphore>(dlsym(handle, "vkCreateSemaphore"));
			vkCreateShaderModule = reinterpret_cast<PFN_vkCreateShaderModule>(vkGetInstanceProcAddr(nullptr, "vkCreateShaderModule"));
			if (!vkCreateShaderModule) vkCreateShaderModule = reinterpret_cast<PFN_vkCreateShaderModule>(dlsym(handle, "vkCreateShaderModule"));
			vkDestroyBuffer = reinterpret_cast<PFN_vkDestroyBuffer>(vkGetInstanceProcAddr(nullptr, "vkDestroyBuffer"));
			if (!vkDestroyBuffer) vkDestroyBuffer = reinterpret_cast<PFN_vkDestroyBuffer>(dlsym(handle, "vkDestroyBuffer"));
			vkDestroyBufferView = reinterpret_cast<PFN_vkDestroyBufferView>(vkGetInstanceProcAddr(nullptr, "vkDestroyBufferView"));
			if (!vkDestroyBufferView) vkDestroyBufferView = reinterpret_cast<PFN_vkDestroyBufferView>(dlsym(handle, "vkDestroyBufferView"));
			vkDestroyCommandPool = reinterpret_cast<PFN_vkDestroyCommandPool>(vkGetInstanceProcAddr(nullptr, "vkDestroyCommandPool"));
			if (!vkDestroyCommandPool) vkDestroyCommandPool = reinterpret_cast<PFN_vkDestroyCommandPool>(dlsym(handle, "vkDestroyCommandPool"));
			vkDestroyDescriptorPool = reinterpret_cast<PFN_vkDestroyDescriptorPool>(vkGetInstanceProcAddr(nullptr, "vkDestroyDescriptorPool"));
			if (!vkDestroyDescriptorPool) vkDestroyDescriptorPool = reinterpret_cast<PFN_vkDestroyDescriptorPool>(dlsym(handle, "vkDestroyDescriptorPool"));
			vkDestroyDescriptorSetLayout = reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(vkGetInstanceProcAddr(nullptr, "vkDestroyDescriptorSetLayout"));
			if (!vkDestroyDescriptorSetLayout) vkDestroyDescriptorSetLayout = reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(dlsym(handle, "vkDestroyDescriptorSetLayout"));
			vkDestroyDevice = reinterpret_cast<PFN_vkDestroyDevice>(vkGetInstanceProcAddr(nullptr, "vkDestroyDevice"));
			if (!vkDestroyDevice) vkDestroyDevice = reinterpret_cast<PFN_vkDestroyDevice>(dlsym(handle, "vkDestroyDevice"));
			vkDestroyEvent = reinterpret_cast<PFN_vkDestroyEvent>(vkGetInstanceProcAddr(nullptr, "vkDestroyEvent"));
			if (!vkDestroyEvent) vkDestroyEvent = reinterpret_cast<PFN_vkDestroyEvent>(dlsym(handle, "vkDestroyEvent"));
			vkDestroyFence = reinterpret_cast<PFN_vkDestroyFence>(vkGetInstanceProcAddr(nullptr, "vkDestroyFence"));
			if (!vkDestroyFence) vkDestroyFence = reinterpret_cast<PFN_vkDestroyFence>(dlsym(handle, "vkDestroyFence"));
			vkDestroyFramebuffer = reinterpret_cast<PFN_vkDestroyFramebuffer>(vkGetInstanceProcAddr(nullptr, "vkDestroyFramebuffer"));
			if (!vkDestroyFramebuffer) vkDestroyFramebuffer = reinterpret_cast<PFN_vkDestroyFramebuffer>(dlsym(handle, "vkDestroyFramebuffer"));
			vkDestroyImage = reinterpret_cast<PFN_vkDestroyImage>(vkGetInstanceProcAddr(nullptr, "vkDestroyImage"));
			if (!vkDestroyImage) vkDestroyImage = reinterpret_cast<PFN_vkDestroyImage>(dlsym(handle, "vkDestroyImage"));
			vkDestroyImageView = reinterpret_cast<PFN_vkDestroyImageView>(vkGetInstanceProcAddr(nullptr, "vkDestroyImageView"));
			if (!vkDestroyImageView) vkDestroyImageView = reinterpret_cast<PFN_vkDestroyImageView>(dlsym(handle, "vkDestroyImageView"));
			vkDestroyInstance = reinterpret_cast<PFN_vkDestroyInstance>(vkGetInstanceProcAddr(nullptr, "vkDestroyInstance"));
			if (!vkDestroyInstance) vkDestroyInstance = reinterpret_cast<PFN_vkDestroyInstance>(dlsym(handle, "vkDestroyInstance"));
			vkDestroyPipeline = reinterpret_cast<PFN_vkDestroyPipeline>(vkGetInstanceProcAddr(nullptr, "vkDestroyPipeline"));
			if (!vkDestroyPipeline) vkDestroyPipeline = reinterpret_cast<PFN_vkDestroyPipeline>(dlsym(handle, "vkDestroyPipeline"));
			vkDestroyPipelineCache = reinterpret_cast<PFN_vkDestroyPipelineCache>(vkGetInstanceProcAddr(nullptr, "vkDestroyPipelineCache"));
			if (!vkDestroyPipelineCache) vkDestroyPipelineCache = reinterpret_cast<PFN_vkDestroyPipelineCache>(dlsym(handle, "vkDestroyPipelineCache"));
			vkGetPipelineCacheData = reinterpret_cast<PFN_vkGetPipelineCacheData>(vkGetInstanceProcAddr(nullptr, "vkGetPipelineCacheData"));
			if (!vkGetPipelineCacheData) vkGetPipelineCacheData = reinterpret_cast<PFN_vkGetPipelineCacheData>(dlsym(handle, "vkGetPipelineCacheData"));
			vkDestroyPipelineLayout = reinterpret_cast<PFN_vkDestroyPipelineLayout>(vkGetInstanceProcAddr(nullptr, "vkDestroyPipelineLayout"));
			if (!vkDestroyPipelineLayout) vkDestroyPipelineLayout = reinterpret_cast<PFN_vkDestroyPipelineLayout>(dlsym(handle, "vkDestroyPipelineLayout"));
			vkDestroyQueryPool = reinterpret_cast<PFN_vkDestroyQueryPool>(vkGetInstanceProcAddr(nullptr, "vkDestroyQueryPool"));
			if (!vkDestroyQueryPool) vkDestroyQueryPool = reinterpret_cast<PFN_vkDestroyQueryPool>(dlsym(handle, "vkDestroyQueryPool"));
			vkDestroyRenderPass = reinterpret_cast<PFN_vkDestroyRenderPass>(vkGetInstanceProcAddr(nullptr, "vkDestroyRenderPass"));
			if (!vkDestroyRenderPass) vkDestroyRenderPass = reinterpret_cast<PFN_vkDestroyRenderPass>(dlsym(handle, "vkDestroyRenderPass"));
			vkDestroySampler = reinterpret_cast<PFN_vkDestroySampler>(vkGetInstanceProcAddr(nullptr, "vkDestroySampler"));
			if (!vkDestroySampler) vkDestroySampler = reinterpret_cast<PFN_vkDestroySampler>(dlsym(handle, "vkDestroySampler"));
			vkDestroySemaphore = reinterpret_cast<PFN_vkDestroySemaphore>(vkGetInstanceProcAddr(nullptr, "vkDestroySemaphore"));
			if (!vkDestroySemaphore) vkDestroySemaphore = reinterpret_cast<PFN_vkDestroySemaphore>(dlsym(handle, "vkDestroySemaphore"));
			vkDestroyShaderModule = reinterpret_cast<PFN_vkDestroyShaderModule>(vkGetInstanceProcAddr(nullptr, "vkDestroyShaderModule"));
			if (!vkDestroyShaderModule) vkDestroyShaderModule = reinterpret_cast<PFN_vkDestroyShaderModule>(dlsym(handle, "vkDestroyShaderModule"));
			vkDestroySurfaceKHR = reinterpret_cast<PFN_vkDestroySurfaceKHR>(vkGetInstanceProcAddr(nullptr, "vkDestroySurfaceKHR"));
			if (!vkDestroySurfaceKHR) vkDestroySurfaceKHR = reinterpret_cast<PFN_vkDestroySurfaceKHR>(dlsym(handle, "vkDestroySurfaceKHR"));
			vkDeviceWaitIdle = reinterpret_cast<PFN_vkDeviceWaitIdle>(vkGetInstanceProcAddr(nullptr, "vkDeviceWaitIdle"));
			if (!vkDeviceWaitIdle) vkDeviceWaitIdle = reinterpret_cast<PFN_vkDeviceWaitIdle>(dlsym(handle, "vkDeviceWaitIdle"));
			vkEndCommandBuffer = reinterpret_cast<PFN_vkEndCommandBuffer>(vkGetInstanceProcAddr(nullptr, "vkEndCommandBuffer"));
			if (!vkEndCommandBuffer) vkEndCommandBuffer = reinterpret_cast<PFN_vkEndCommandBuffer>(dlsym(handle, "vkEndCommandBuffer"));
			vkEnumerateDeviceExtensionProperties = reinterpret_cast<PFN_vkEnumerateDeviceExtensionProperties>(vkGetInstanceProcAddr(nullptr, "vkEnumerateDeviceExtensionProperties"));
			if (!vkEnumerateDeviceExtensionProperties) vkEnumerateDeviceExtensionProperties = reinterpret_cast<PFN_vkEnumerateDeviceExtensionProperties>(dlsym(handle, "vkEnumerateDeviceExtensionProperties"));
			vkEnumerateInstanceExtensionProperties = reinterpret_cast<PFN_vkEnumerateInstanceExtensionProperties>(vkGetInstanceProcAddr(nullptr, "vkEnumerateInstanceExtensionProperties"));
			if (!vkEnumerateInstanceExtensionProperties) vkEnumerateInstanceExtensionProperties = reinterpret_cast<PFN_vkEnumerateInstanceExtensionProperties>(dlsym(handle, "vkEnumerateInstanceExtensionProperties"));
			vkEnumeratePhysicalDevices = reinterpret_cast<PFN_vkEnumeratePhysicalDevices>(vkGetInstanceProcAddr(nullptr, "vkEnumeratePhysicalDevices"));
			if (!vkEnumeratePhysicalDevices) vkEnumeratePhysicalDevices = reinterpret_cast<PFN_vkEnumeratePhysicalDevices>(dlsym(handle, "vkEnumeratePhysicalDevices"));
			vkFlushMappedMemoryRanges = reinterpret_cast<PFN_vkFlushMappedMemoryRanges>(vkGetInstanceProcAddr(nullptr, "vkFlushMappedMemoryRanges"));
			if (!vkFlushMappedMemoryRanges) vkFlushMappedMemoryRanges = reinterpret_cast<PFN_vkFlushMappedMemoryRanges>(dlsym(handle, "vkFlushMappedMemoryRanges"));
			vkFreeCommandBuffers = reinterpret_cast<PFN_vkFreeCommandBuffers>(vkGetInstanceProcAddr(nullptr, "vkFreeCommandBuffers"));
			if (!vkFreeCommandBuffers) vkFreeCommandBuffers = reinterpret_cast<PFN_vkFreeCommandBuffers>(dlsym(handle, "vkFreeCommandBuffers"));
			vkFreeMemory = reinterpret_cast<PFN_vkFreeMemory>(vkGetInstanceProcAddr(nullptr, "vkFreeMemory"));
			if (!vkFreeMemory) vkFreeMemory = reinterpret_cast<PFN_vkFreeMemory>(dlsym(handle, "vkFreeMemory"));
			vkGetBufferMemoryRequirements = reinterpret_cast<PFN_vkGetBufferMemoryRequirements>(vkGetInstanceProcAddr(nullptr, "vkGetBufferMemoryRequirements"));
			if (!vkGetBufferMemoryRequirements) vkGetBufferMemoryRequirements = reinterpret_cast<PFN_vkGetBufferMemoryRequirements>(dlsym(handle, "vkGetBufferMemoryRequirements"));
			vkGetBufferMemoryRequirements2 = reinterpret_cast<PFN_vkGetBufferMemoryRequirements2>(vkGetInstanceProcAddr(nullptr, "vkGetBufferMemoryRequirements2"));
			if (!vkGetBufferMemoryRequirements2) vkGetBufferMemoryRequirements2 = reinterpret_cast<PFN_vkGetBufferMemoryRequirements2>(dlsym(handle, "vkGetBufferMemoryRequirements2"));
			vkGetDeviceProcAddr = reinterpret_cast<PFN_vkGetDeviceProcAddr>(vkGetInstanceProcAddr(nullptr, "vkGetDeviceProcAddr"));
			if (!vkGetDeviceProcAddr) vkGetDeviceProcAddr = reinterpret_cast<PFN_vkGetDeviceProcAddr>(dlsym(handle, "vkGetDeviceProcAddr"));
			vkGetDeviceQueue = reinterpret_cast<PFN_vkGetDeviceQueue>(vkGetInstanceProcAddr(nullptr, "vkGetDeviceQueue"));
			if (!vkGetDeviceQueue) vkGetDeviceQueue = reinterpret_cast<PFN_vkGetDeviceQueue>(dlsym(handle, "vkGetDeviceQueue"));
			vkGetEventStatus = reinterpret_cast<PFN_vkGetEventStatus>(vkGetInstanceProcAddr(nullptr, "vkGetEventStatus"));
			if (!vkGetEventStatus) vkGetEventStatus = reinterpret_cast<PFN_vkGetEventStatus>(dlsym(handle, "vkGetEventStatus"));
			vkGetFenceStatus = reinterpret_cast<PFN_vkGetFenceStatus>(vkGetInstanceProcAddr(nullptr, "vkGetFenceStatus"));
			if (!vkGetFenceStatus) vkGetFenceStatus = reinterpret_cast<PFN_vkGetFenceStatus>(dlsym(handle, "vkGetFenceStatus"));
			vkGetImageMemoryRequirements = reinterpret_cast<PFN_vkGetImageMemoryRequirements>(vkGetInstanceProcAddr(nullptr, "vkGetImageMemoryRequirements"));
			if (!vkGetImageMemoryRequirements) vkGetImageMemoryRequirements = reinterpret_cast<PFN_vkGetImageMemoryRequirements>(dlsym(handle, "vkGetImageMemoryRequirements"));
			vkGetImageMemoryRequirements2 = reinterpret_cast<PFN_vkGetImageMemoryRequirements2>(vkGetInstanceProcAddr(nullptr, "vkGetImageMemoryRequirements2"));
			if (!vkGetImageMemoryRequirements2) vkGetImageMemoryRequirements2 = reinterpret_cast<PFN_vkGetImageMemoryRequirements2>(dlsym(handle, "vkGetImageMemoryRequirements2"));
			vkGetImageSubresourceLayout = reinterpret_cast<PFN_vkGetImageSubresourceLayout>(vkGetInstanceProcAddr(nullptr, "vkGetImageSubresourceLayout"));
			if (!vkGetImageSubresourceLayout) vkGetImageSubresourceLayout = reinterpret_cast<PFN_vkGetImageSubresourceLayout>(dlsym(handle, "vkGetImageSubresourceLayout"));
			vkGetPhysicalDeviceFeatures = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceFeatures"));
			if (!vkGetPhysicalDeviceFeatures) vkGetPhysicalDeviceFeatures = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures>(dlsym(handle, "vkGetPhysicalDeviceFeatures"));
			vkGetPhysicalDeviceFeatures2 = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures2>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceFeatures2"));
			if (!vkGetPhysicalDeviceFeatures2) vkGetPhysicalDeviceFeatures2 = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures2>(dlsym(handle, "vkGetPhysicalDeviceFeatures2"));
			vkGetPhysicalDeviceFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceFormatProperties"));
			if (!vkGetPhysicalDeviceFormatProperties) vkGetPhysicalDeviceFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties>(dlsym(handle, "vkGetPhysicalDeviceFormatProperties"));
			vkGetPhysicalDeviceMemoryProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceMemoryProperties"));
			if (!vkGetPhysicalDeviceMemoryProperties) vkGetPhysicalDeviceMemoryProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties>(dlsym(handle, "vkGetPhysicalDeviceMemoryProperties"));
			vkGetPhysicalDeviceMemoryProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties2>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceMemoryProperties2"));
			if (!vkGetPhysicalDeviceMemoryProperties2) vkGetPhysicalDeviceMemoryProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties2>(dlsym(handle, "vkGetPhysicalDeviceMemoryProperties2"));
			vkGetPhysicalDeviceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceProperties"));
			if (!vkGetPhysicalDeviceProperties) vkGetPhysicalDeviceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties>(dlsym(handle, "vkGetPhysicalDeviceProperties"));
			vkGetPhysicalDeviceProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties2>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceProperties2"));
			if (!vkGetPhysicalDeviceProperties2) vkGetPhysicalDeviceProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties2>(dlsym(handle, "vkGetPhysicalDeviceProperties2"));
			vkGetPhysicalDeviceQueueFamilyProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceQueueFamilyProperties>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceQueueFamilyProperties"));
			if (!vkGetPhysicalDeviceQueueFamilyProperties) vkGetPhysicalDeviceQueueFamilyProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceQueueFamilyProperties>(dlsym(handle, "vkGetPhysicalDeviceQueueFamilyProperties"));
			vkGetPhysicalDeviceSurfaceCapabilitiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR"));
			if (!vkGetPhysicalDeviceSurfaceCapabilitiesKHR) vkGetPhysicalDeviceSurfaceCapabilitiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR>(dlsym(handle, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR"));
			vkGetPhysicalDeviceSurfaceFormatsKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceFormatsKHR>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceSurfaceFormatsKHR"));
			if (!vkGetPhysicalDeviceSurfaceFormatsKHR) vkGetPhysicalDeviceSurfaceFormatsKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceFormatsKHR>(dlsym(handle, "vkGetPhysicalDeviceSurfaceFormatsKHR"));
			vkGetPhysicalDeviceSurfacePresentModesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfacePresentModesKHR>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceSurfacePresentModesKHR"));
			if (!vkGetPhysicalDeviceSurfacePresentModesKHR) vkGetPhysicalDeviceSurfacePresentModesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfacePresentModesKHR>(dlsym(handle, "vkGetPhysicalDeviceSurfacePresentModesKHR"));
			vkGetPhysicalDeviceSurfaceSupportKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceSupportKHR>(vkGetInstanceProcAddr(nullptr, "vkGetPhysicalDeviceSurfaceSupportKHR"));
			if (!vkGetPhysicalDeviceSurfaceSupportKHR) vkGetPhysicalDeviceSurfaceSupportKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceSupportKHR>(dlsym(handle, "vkGetPhysicalDeviceSurfaceSupportKHR"));
			vkGetQueryPoolResults = reinterpret_cast<PFN_vkGetQueryPoolResults>(vkGetInstanceProcAddr(nullptr, "vkGetQueryPoolResults"));
			if (!vkGetQueryPoolResults) vkGetQueryPoolResults = reinterpret_cast<PFN_vkGetQueryPoolResults>(dlsym(handle, "vkGetQueryPoolResults"));
			vkCmdWriteTimestamp = reinterpret_cast<PFN_vkCmdWriteTimestamp>(vkGetInstanceProcAddr(nullptr, "vkCmdWriteTimestamp"));
			if (!vkCmdWriteTimestamp) vkCmdWriteTimestamp = reinterpret_cast<PFN_vkCmdWriteTimestamp>(dlsym(handle, "vkCmdWriteTimestamp"));
			vkInvalidateMappedMemoryRanges = reinterpret_cast<PFN_vkInvalidateMappedMemoryRanges>(vkGetInstanceProcAddr(nullptr, "vkInvalidateMappedMemoryRanges"));
			if (!vkInvalidateMappedMemoryRanges) vkInvalidateMappedMemoryRanges = reinterpret_cast<PFN_vkInvalidateMappedMemoryRanges>(dlsym(handle, "vkInvalidateMappedMemoryRanges"));
			vkMapMemory = reinterpret_cast<PFN_vkMapMemory>(vkGetInstanceProcAddr(nullptr, "vkMapMemory"));
			if (!vkMapMemory) vkMapMemory = reinterpret_cast<PFN_vkMapMemory>(dlsym(handle, "vkMapMemory"));
			vkQueueSubmit = reinterpret_cast<PFN_vkQueueSubmit>(vkGetInstanceProcAddr(nullptr, "vkQueueSubmit"));
			if (!vkQueueSubmit) vkQueueSubmit = reinterpret_cast<PFN_vkQueueSubmit>(dlsym(handle, "vkQueueSubmit"));
			vkResetCommandBuffer = reinterpret_cast<PFN_vkResetCommandBuffer>(vkGetInstanceProcAddr(nullptr, "vkResetCommandBuffer"));
			if (!vkResetCommandBuffer) vkResetCommandBuffer = reinterpret_cast<PFN_vkResetCommandBuffer>(dlsym(handle, "vkResetCommandBuffer"));
			vkResetDescriptorPool = reinterpret_cast<PFN_vkResetDescriptorPool>(vkGetInstanceProcAddr(nullptr, "vkResetDescriptorPool"));
			if (!vkResetDescriptorPool) vkResetDescriptorPool = reinterpret_cast<PFN_vkResetDescriptorPool>(dlsym(handle, "vkResetDescriptorPool"));
			vkResetEvent = reinterpret_cast<PFN_vkResetEvent>(vkGetInstanceProcAddr(nullptr, "vkResetEvent"));
			if (!vkResetEvent) vkResetEvent = reinterpret_cast<PFN_vkResetEvent>(dlsym(handle, "vkResetEvent"));
			vkResetFences = reinterpret_cast<PFN_vkResetFences>(vkGetInstanceProcAddr(nullptr, "vkResetFences"));
			if (!vkResetFences) vkResetFences = reinterpret_cast<PFN_vkResetFences>(dlsym(handle, "vkResetFences"));
			vkSetEvent = reinterpret_cast<PFN_vkSetEvent>(vkGetInstanceProcAddr(nullptr, "vkSetEvent"));
			if (!vkSetEvent) vkSetEvent = reinterpret_cast<PFN_vkSetEvent>(dlsym(handle, "vkSetEvent"));
			vkUnmapMemory = reinterpret_cast<PFN_vkUnmapMemory>(vkGetInstanceProcAddr(nullptr, "vkUnmapMemory"));
			if (!vkUnmapMemory) vkUnmapMemory = reinterpret_cast<PFN_vkUnmapMemory>(dlsym(handle, "vkUnmapMemory"));
			vkUpdateDescriptorSets = reinterpret_cast<PFN_vkUpdateDescriptorSets>(vkGetInstanceProcAddr(nullptr, "vkUpdateDescriptorSets"));
			if (!vkUpdateDescriptorSets) vkUpdateDescriptorSets = reinterpret_cast<PFN_vkUpdateDescriptorSets>(dlsym(handle, "vkUpdateDescriptorSets"));
			vkWaitForFences = reinterpret_cast<PFN_vkWaitForFences>(vkGetInstanceProcAddr(nullptr, "vkWaitForFences"));
			if (!vkWaitForFences) vkWaitForFences = reinterpret_cast<PFN_vkWaitForFences>(dlsym(handle, "vkWaitForFences"));

			if (!vkCreateInstance)
			{
				g_error = "driver exports no vkCreateInstance";
				return false;
			}

			return true;
		}
	}

	void resolve_instance(VkInstance instance)
	{
		if (!instance || !vkGetInstanceProcAddr) return;

		if (auto p = vkGetInstanceProcAddr(instance, "vkAcquireNextImageKHR")) vkAcquireNextImageKHR = reinterpret_cast<PFN_vkAcquireNextImageKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkAllocateCommandBuffers")) vkAllocateCommandBuffers = reinterpret_cast<PFN_vkAllocateCommandBuffers>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkAllocateDescriptorSets")) vkAllocateDescriptorSets = reinterpret_cast<PFN_vkAllocateDescriptorSets>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkAllocateMemory")) vkAllocateMemory = reinterpret_cast<PFN_vkAllocateMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkBeginCommandBuffer")) vkBeginCommandBuffer = reinterpret_cast<PFN_vkBeginCommandBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkBindBufferMemory")) vkBindBufferMemory = reinterpret_cast<PFN_vkBindBufferMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkBindBufferMemory2")) vkBindBufferMemory2 = reinterpret_cast<PFN_vkBindBufferMemory2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkBindImageMemory")) vkBindImageMemory = reinterpret_cast<PFN_vkBindImageMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkBindImageMemory2")) vkBindImageMemory2 = reinterpret_cast<PFN_vkBindImageMemory2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBeginQuery")) vkCmdBeginQuery = reinterpret_cast<PFN_vkCmdBeginQuery>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBeginRenderPass")) vkCmdBeginRenderPass = reinterpret_cast<PFN_vkCmdBeginRenderPass>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBindDescriptorSets")) vkCmdBindDescriptorSets = reinterpret_cast<PFN_vkCmdBindDescriptorSets>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBindIndexBuffer")) vkCmdBindIndexBuffer = reinterpret_cast<PFN_vkCmdBindIndexBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBindPipeline")) vkCmdBindPipeline = reinterpret_cast<PFN_vkCmdBindPipeline>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBindVertexBuffers")) vkCmdBindVertexBuffers = reinterpret_cast<PFN_vkCmdBindVertexBuffers>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdBlitImage")) vkCmdBlitImage = reinterpret_cast<PFN_vkCmdBlitImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdClearAttachments")) vkCmdClearAttachments = reinterpret_cast<PFN_vkCmdClearAttachments>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdClearColorImage")) vkCmdClearColorImage = reinterpret_cast<PFN_vkCmdClearColorImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdClearDepthStencilImage")) vkCmdClearDepthStencilImage = reinterpret_cast<PFN_vkCmdClearDepthStencilImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdCopyBuffer")) vkCmdCopyBuffer = reinterpret_cast<PFN_vkCmdCopyBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdCopyBufferToImage")) vkCmdCopyBufferToImage = reinterpret_cast<PFN_vkCmdCopyBufferToImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdCopyImage")) vkCmdCopyImage = reinterpret_cast<PFN_vkCmdCopyImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdCopyImageToBuffer")) vkCmdCopyImageToBuffer = reinterpret_cast<PFN_vkCmdCopyImageToBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdCopyQueryPoolResults")) vkCmdCopyQueryPoolResults = reinterpret_cast<PFN_vkCmdCopyQueryPoolResults>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdDispatch")) vkCmdDispatch = reinterpret_cast<PFN_vkCmdDispatch>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdDraw")) vkCmdDraw = reinterpret_cast<PFN_vkCmdDraw>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdDrawIndexed")) vkCmdDrawIndexed = reinterpret_cast<PFN_vkCmdDrawIndexed>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdEndQuery")) vkCmdEndQuery = reinterpret_cast<PFN_vkCmdEndQuery>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdEndRenderPass")) vkCmdEndRenderPass = reinterpret_cast<PFN_vkCmdEndRenderPass>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdFillBuffer")) vkCmdFillBuffer = reinterpret_cast<PFN_vkCmdFillBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdPipelineBarrier")) vkCmdPipelineBarrier = reinterpret_cast<PFN_vkCmdPipelineBarrier>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdPushConstants")) vkCmdPushConstants = reinterpret_cast<PFN_vkCmdPushConstants>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdResetQueryPool")) vkCmdResetQueryPool = reinterpret_cast<PFN_vkCmdResetQueryPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetBlendConstants")) vkCmdSetBlendConstants = reinterpret_cast<PFN_vkCmdSetBlendConstants>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetDepthBias")) vkCmdSetDepthBias = reinterpret_cast<PFN_vkCmdSetDepthBias>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetDepthBounds")) vkCmdSetDepthBounds = reinterpret_cast<PFN_vkCmdSetDepthBounds>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetEvent")) vkCmdSetEvent = reinterpret_cast<PFN_vkCmdSetEvent>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetLineWidth")) vkCmdSetLineWidth = reinterpret_cast<PFN_vkCmdSetLineWidth>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetScissor")) vkCmdSetScissor = reinterpret_cast<PFN_vkCmdSetScissor>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetStencilCompareMask")) vkCmdSetStencilCompareMask = reinterpret_cast<PFN_vkCmdSetStencilCompareMask>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetStencilReference")) vkCmdSetStencilReference = reinterpret_cast<PFN_vkCmdSetStencilReference>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetStencilWriteMask")) vkCmdSetStencilWriteMask = reinterpret_cast<PFN_vkCmdSetStencilWriteMask>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdSetViewport")) vkCmdSetViewport = reinterpret_cast<PFN_vkCmdSetViewport>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdUpdateBuffer")) vkCmdUpdateBuffer = reinterpret_cast<PFN_vkCmdUpdateBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdWaitEvents")) vkCmdWaitEvents = reinterpret_cast<PFN_vkCmdWaitEvents>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateAndroidSurfaceKHR")) vkCreateAndroidSurfaceKHR = reinterpret_cast<PFN_vkCreateAndroidSurfaceKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateBuffer")) vkCreateBuffer = reinterpret_cast<PFN_vkCreateBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateBufferView")) vkCreateBufferView = reinterpret_cast<PFN_vkCreateBufferView>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateCommandPool")) vkCreateCommandPool = reinterpret_cast<PFN_vkCreateCommandPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateComputePipelines")) vkCreateComputePipelines = reinterpret_cast<PFN_vkCreateComputePipelines>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateDescriptorPool")) vkCreateDescriptorPool = reinterpret_cast<PFN_vkCreateDescriptorPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateDescriptorSetLayout")) vkCreateDescriptorSetLayout = reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateDevice")) vkCreateDevice = reinterpret_cast<PFN_vkCreateDevice>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateEvent")) vkCreateEvent = reinterpret_cast<PFN_vkCreateEvent>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateFence")) vkCreateFence = reinterpret_cast<PFN_vkCreateFence>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateFramebuffer")) vkCreateFramebuffer = reinterpret_cast<PFN_vkCreateFramebuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateGraphicsPipelines")) vkCreateGraphicsPipelines = reinterpret_cast<PFN_vkCreateGraphicsPipelines>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateImage")) vkCreateImage = reinterpret_cast<PFN_vkCreateImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateImageView")) vkCreateImageView = reinterpret_cast<PFN_vkCreateImageView>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreatePipelineCache")) vkCreatePipelineCache = reinterpret_cast<PFN_vkCreatePipelineCache>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreatePipelineLayout")) vkCreatePipelineLayout = reinterpret_cast<PFN_vkCreatePipelineLayout>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateQueryPool")) vkCreateQueryPool = reinterpret_cast<PFN_vkCreateQueryPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateRenderPass")) vkCreateRenderPass = reinterpret_cast<PFN_vkCreateRenderPass>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateSampler")) vkCreateSampler = reinterpret_cast<PFN_vkCreateSampler>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateSemaphore")) vkCreateSemaphore = reinterpret_cast<PFN_vkCreateSemaphore>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCreateShaderModule")) vkCreateShaderModule = reinterpret_cast<PFN_vkCreateShaderModule>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyBuffer")) vkDestroyBuffer = reinterpret_cast<PFN_vkDestroyBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyBufferView")) vkDestroyBufferView = reinterpret_cast<PFN_vkDestroyBufferView>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyCommandPool")) vkDestroyCommandPool = reinterpret_cast<PFN_vkDestroyCommandPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyDescriptorPool")) vkDestroyDescriptorPool = reinterpret_cast<PFN_vkDestroyDescriptorPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyDescriptorSetLayout")) vkDestroyDescriptorSetLayout = reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyDevice")) vkDestroyDevice = reinterpret_cast<PFN_vkDestroyDevice>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyEvent")) vkDestroyEvent = reinterpret_cast<PFN_vkDestroyEvent>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyFence")) vkDestroyFence = reinterpret_cast<PFN_vkDestroyFence>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyFramebuffer")) vkDestroyFramebuffer = reinterpret_cast<PFN_vkDestroyFramebuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyImage")) vkDestroyImage = reinterpret_cast<PFN_vkDestroyImage>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyImageView")) vkDestroyImageView = reinterpret_cast<PFN_vkDestroyImageView>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyInstance")) vkDestroyInstance = reinterpret_cast<PFN_vkDestroyInstance>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyPipeline")) vkDestroyPipeline = reinterpret_cast<PFN_vkDestroyPipeline>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyPipelineCache")) vkDestroyPipelineCache = reinterpret_cast<PFN_vkDestroyPipelineCache>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPipelineCacheData")) vkGetPipelineCacheData = reinterpret_cast<PFN_vkGetPipelineCacheData>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyPipelineLayout")) vkDestroyPipelineLayout = reinterpret_cast<PFN_vkDestroyPipelineLayout>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyQueryPool")) vkDestroyQueryPool = reinterpret_cast<PFN_vkDestroyQueryPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyRenderPass")) vkDestroyRenderPass = reinterpret_cast<PFN_vkDestroyRenderPass>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroySampler")) vkDestroySampler = reinterpret_cast<PFN_vkDestroySampler>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroySemaphore")) vkDestroySemaphore = reinterpret_cast<PFN_vkDestroySemaphore>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroyShaderModule")) vkDestroyShaderModule = reinterpret_cast<PFN_vkDestroyShaderModule>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDestroySurfaceKHR")) vkDestroySurfaceKHR = reinterpret_cast<PFN_vkDestroySurfaceKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkDeviceWaitIdle")) vkDeviceWaitIdle = reinterpret_cast<PFN_vkDeviceWaitIdle>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkEndCommandBuffer")) vkEndCommandBuffer = reinterpret_cast<PFN_vkEndCommandBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkEnumerateDeviceExtensionProperties")) vkEnumerateDeviceExtensionProperties = reinterpret_cast<PFN_vkEnumerateDeviceExtensionProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkEnumerateInstanceExtensionProperties")) vkEnumerateInstanceExtensionProperties = reinterpret_cast<PFN_vkEnumerateInstanceExtensionProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkEnumeratePhysicalDevices")) vkEnumeratePhysicalDevices = reinterpret_cast<PFN_vkEnumeratePhysicalDevices>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkFlushMappedMemoryRanges")) vkFlushMappedMemoryRanges = reinterpret_cast<PFN_vkFlushMappedMemoryRanges>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkFreeCommandBuffers")) vkFreeCommandBuffers = reinterpret_cast<PFN_vkFreeCommandBuffers>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkFreeMemory")) vkFreeMemory = reinterpret_cast<PFN_vkFreeMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetBufferMemoryRequirements")) vkGetBufferMemoryRequirements = reinterpret_cast<PFN_vkGetBufferMemoryRequirements>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetBufferMemoryRequirements2")) vkGetBufferMemoryRequirements2 = reinterpret_cast<PFN_vkGetBufferMemoryRequirements2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetDeviceProcAddr")) vkGetDeviceProcAddr = reinterpret_cast<PFN_vkGetDeviceProcAddr>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetDeviceQueue")) vkGetDeviceQueue = reinterpret_cast<PFN_vkGetDeviceQueue>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetEventStatus")) vkGetEventStatus = reinterpret_cast<PFN_vkGetEventStatus>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetFenceStatus")) vkGetFenceStatus = reinterpret_cast<PFN_vkGetFenceStatus>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetImageMemoryRequirements")) vkGetImageMemoryRequirements = reinterpret_cast<PFN_vkGetImageMemoryRequirements>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetImageMemoryRequirements2")) vkGetImageMemoryRequirements2 = reinterpret_cast<PFN_vkGetImageMemoryRequirements2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetImageSubresourceLayout")) vkGetImageSubresourceLayout = reinterpret_cast<PFN_vkGetImageSubresourceLayout>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures")) vkGetPhysicalDeviceFeatures = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures2")) vkGetPhysicalDeviceFeatures2 = reinterpret_cast<PFN_vkGetPhysicalDeviceFeatures2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceFormatProperties")) vkGetPhysicalDeviceFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties")) vkGetPhysicalDeviceMemoryProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceMemoryProperties2")) vkGetPhysicalDeviceMemoryProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceMemoryProperties2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties")) vkGetPhysicalDeviceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2")) vkGetPhysicalDeviceProperties2 = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties2>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties")) vkGetPhysicalDeviceQueueFamilyProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceQueueFamilyProperties>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceCapabilitiesKHR")) vkGetPhysicalDeviceSurfaceCapabilitiesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceFormatsKHR")) vkGetPhysicalDeviceSurfaceFormatsKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceFormatsKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfacePresentModesKHR")) vkGetPhysicalDeviceSurfacePresentModesKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfacePresentModesKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceSurfaceSupportKHR")) vkGetPhysicalDeviceSurfaceSupportKHR = reinterpret_cast<PFN_vkGetPhysicalDeviceSurfaceSupportKHR>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkGetQueryPoolResults")) vkGetQueryPoolResults = reinterpret_cast<PFN_vkGetQueryPoolResults>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkCmdWriteTimestamp")) vkCmdWriteTimestamp = reinterpret_cast<PFN_vkCmdWriteTimestamp>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkInvalidateMappedMemoryRanges")) vkInvalidateMappedMemoryRanges = reinterpret_cast<PFN_vkInvalidateMappedMemoryRanges>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkMapMemory")) vkMapMemory = reinterpret_cast<PFN_vkMapMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkQueueSubmit")) vkQueueSubmit = reinterpret_cast<PFN_vkQueueSubmit>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkResetCommandBuffer")) vkResetCommandBuffer = reinterpret_cast<PFN_vkResetCommandBuffer>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkResetDescriptorPool")) vkResetDescriptorPool = reinterpret_cast<PFN_vkResetDescriptorPool>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkResetEvent")) vkResetEvent = reinterpret_cast<PFN_vkResetEvent>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkResetFences")) vkResetFences = reinterpret_cast<PFN_vkResetFences>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkSetEvent")) vkSetEvent = reinterpret_cast<PFN_vkSetEvent>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkUnmapMemory")) vkUnmapMemory = reinterpret_cast<PFN_vkUnmapMemory>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkUpdateDescriptorSets")) vkUpdateDescriptorSets = reinterpret_cast<PFN_vkUpdateDescriptorSets>(p);
		if (auto p = vkGetInstanceProcAddr(instance, "vkWaitForFences")) vkWaitForFences = reinterpret_cast<PFN_vkWaitForFences>(p);
	}

	void* set_driver_handle(void* handle)
	{
		std::lock_guard lock(g_mutex);
		g_error.clear();

		void* previous = g_handle;

		if (!handle)
		{
			// Clearing the custom driver: fall back to the system one. Resolve now
			// rather than at next use, so a broken fallback is reported while
			// there is still a caller to report it to.
			handle = dlopen("libvulkan.so", RTLD_NOW | RTLD_LOCAL);
			g_custom = false;

			if (!handle)
			{
				const char* err = dlerror();
				g_error = err ? err : "libvulkan.so could not be opened";
				vk_loader.fatal("no Vulkan driver available: %s", g_error);
				return previous;
			}
		}
		else
		{
			g_custom = true;
		}

		if (!resolve_all(handle))
		{
			vk_loader.error("driver opened but unusable (%s); keeping the previous one", g_error);

			// Restore rather than leave the table half-resolved: a partially
			// populated table crashes on the first null entry, a long way from
			// the actual cause.
			g_custom = false;
			if (previous && resolve_all(previous))
			{
				// We went back to `previous`, so the caller must NOT close it.
				return nullptr;
			}

			return previous;
		}

		g_handle = handle;

		// "custom" describes the handle we were given, not necessarily the driver that
		// answers through it: adrenotools falls back to the system driver inside that
		// handle when its own dlopen fails, and says so only to logcat. The identity
		// logged by physical_device::create is what actually answered.
		vk_loader.success("Vulkan dispatch bound to the %s driver handle", g_custom ? "custom" : "system");
		return previous;
	}

	bool ensure_loaded()
	{
		{
			std::lock_guard lock(g_mutex);
			if (g_handle) return true;
		}

		set_driver_handle(nullptr);

		std::lock_guard lock(g_mutex);
		return g_handle != nullptr;
	}

	bool using_custom_driver()
	{
		std::lock_guard lock(g_mutex);
		return g_custom;
	}

	const char* last_error()
	{
		std::lock_guard lock(g_mutex);
		return g_error.c_str();
	}
}

#endif // __ANDROID__
