// GENERATED by android/tools/gen_vk_loader.py -- do not edit by hand.
// See that script for why this shim exists.
#pragma once

#ifdef __ANDROID__

#include "VulkanAPI.h"

namespace vk::android
{
	// Point the dispatch table at an already-opened driver.
	//
	// The handle comes from the JNI glue, which is what calls adrenotools --
	// that keeps the dependency app-side and out of the emulator core. Pass
	// nullptr to fall back to the system libvulkan.so.
	//
	// Returns the PREVIOUS handle so the caller can dlclose it. The caller must
	// not do so while the old driver still owns live objects.
	void* set_driver_handle(void* handle);

	// Load the system driver if set_driver_handle() was never called. Safe to
	// call repeatedly and from any thread.
	bool ensure_loaded();

	// Re-resolve instance-level entry points once the VkInstance exists. Some
	// functions legitimately return null from vkGetInstanceProcAddr(nullptr, ..),
	// so the initial table has holes until this runs.
	void resolve_instance(VkInstance instance);

	// True when the table currently points at a user-supplied driver.
	bool using_custom_driver();

	// Human-readable reason the last load failed, or empty.
	const char* last_error();
}

extern "C"
{
	extern PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;
	extern PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
	extern PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
	extern PFN_vkAllocateMemory vkAllocateMemory;
	extern PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
	extern PFN_vkBindBufferMemory vkBindBufferMemory;
	extern PFN_vkBindBufferMemory2 vkBindBufferMemory2;
	extern PFN_vkBindImageMemory vkBindImageMemory;
	extern PFN_vkBindImageMemory2 vkBindImageMemory2;
	extern PFN_vkCmdBeginQuery vkCmdBeginQuery;
	extern PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;
	extern PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
	extern PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
	extern PFN_vkCmdBindPipeline vkCmdBindPipeline;
	extern PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
	extern PFN_vkCmdBlitImage vkCmdBlitImage;
	extern PFN_vkCmdClearAttachments vkCmdClearAttachments;
	extern PFN_vkCmdClearColorImage vkCmdClearColorImage;
	extern PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage;
	extern PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
	extern PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
	extern PFN_vkCmdCopyImage vkCmdCopyImage;
	extern PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer;
	extern PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults;
	extern PFN_vkCmdDispatch vkCmdDispatch;
	extern PFN_vkCmdDraw vkCmdDraw;
	extern PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
	extern PFN_vkCmdEndQuery vkCmdEndQuery;
	extern PFN_vkCmdEndRenderPass vkCmdEndRenderPass;
	extern PFN_vkCmdFillBuffer vkCmdFillBuffer;
	extern PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
	extern PFN_vkCmdPushConstants vkCmdPushConstants;
	extern PFN_vkCmdResetQueryPool vkCmdResetQueryPool;
	extern PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants;
	extern PFN_vkCmdSetDepthBias vkCmdSetDepthBias;
	extern PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds;
	extern PFN_vkCmdSetEvent vkCmdSetEvent;
	extern PFN_vkCmdSetLineWidth vkCmdSetLineWidth;
	extern PFN_vkCmdSetScissor vkCmdSetScissor;
	extern PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask;
	extern PFN_vkCmdSetStencilReference vkCmdSetStencilReference;
	extern PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask;
	extern PFN_vkCmdSetViewport vkCmdSetViewport;
	extern PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer;
	extern PFN_vkCmdWaitEvents vkCmdWaitEvents;
	extern PFN_vkCreateAndroidSurfaceKHR vkCreateAndroidSurfaceKHR;
	extern PFN_vkCreateBuffer vkCreateBuffer;
	extern PFN_vkCreateBufferView vkCreateBufferView;
	extern PFN_vkCreateCommandPool vkCreateCommandPool;
	extern PFN_vkCreateComputePipelines vkCreateComputePipelines;
	extern PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
	extern PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
	extern PFN_vkCreateDevice vkCreateDevice;
	extern PFN_vkCreateEvent vkCreateEvent;
	extern PFN_vkCreateFence vkCreateFence;
	extern PFN_vkCreateFramebuffer vkCreateFramebuffer;
	extern PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
	extern PFN_vkCreateImage vkCreateImage;
	extern PFN_vkCreateImageView vkCreateImageView;
	extern PFN_vkCreateInstance vkCreateInstance;
	extern PFN_vkCreatePipelineCache vkCreatePipelineCache;
	extern PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
	extern PFN_vkCreateQueryPool vkCreateQueryPool;
	extern PFN_vkCreateRenderPass vkCreateRenderPass;
	extern PFN_vkCreateSampler vkCreateSampler;
	extern PFN_vkCreateSemaphore vkCreateSemaphore;
	extern PFN_vkCreateShaderModule vkCreateShaderModule;
	extern PFN_vkDestroyBuffer vkDestroyBuffer;
	extern PFN_vkDestroyBufferView vkDestroyBufferView;
	extern PFN_vkDestroyCommandPool vkDestroyCommandPool;
	extern PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
	extern PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
	extern PFN_vkDestroyDevice vkDestroyDevice;
	extern PFN_vkDestroyEvent vkDestroyEvent;
	extern PFN_vkDestroyFence vkDestroyFence;
	extern PFN_vkDestroyFramebuffer vkDestroyFramebuffer;
	extern PFN_vkDestroyImage vkDestroyImage;
	extern PFN_vkDestroyImageView vkDestroyImageView;
	extern PFN_vkDestroyInstance vkDestroyInstance;
	extern PFN_vkDestroyPipeline vkDestroyPipeline;
	extern PFN_vkDestroyPipelineCache vkDestroyPipelineCache;
	extern PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
	extern PFN_vkDestroyQueryPool vkDestroyQueryPool;
	extern PFN_vkDestroyRenderPass vkDestroyRenderPass;
	extern PFN_vkDestroySampler vkDestroySampler;
	extern PFN_vkDestroySemaphore vkDestroySemaphore;
	extern PFN_vkDestroyShaderModule vkDestroyShaderModule;
	extern PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR;
	extern PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
	extern PFN_vkEndCommandBuffer vkEndCommandBuffer;
	extern PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;
	extern PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties;
	extern PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
	extern PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;
	extern PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
	extern PFN_vkFreeMemory vkFreeMemory;
	extern PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
	extern PFN_vkGetBufferMemoryRequirements2 vkGetBufferMemoryRequirements2;
	extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;
	extern PFN_vkGetDeviceQueue vkGetDeviceQueue;
	extern PFN_vkGetEventStatus vkGetEventStatus;
	extern PFN_vkGetFenceStatus vkGetFenceStatus;
	extern PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
	extern PFN_vkGetImageMemoryRequirements2 vkGetImageMemoryRequirements2;
	extern PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout;
	extern PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;
	extern PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures;
	extern PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2;
	extern PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;
	extern PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
	extern PFN_vkGetPhysicalDeviceMemoryProperties2 vkGetPhysicalDeviceMemoryProperties2;
	extern PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
	extern PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2;
	extern PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
	extern PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
	extern PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;
	extern PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;
	extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;
	extern PFN_vkGetQueryPoolResults vkGetQueryPoolResults;
	extern PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp;
	extern PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;
	extern PFN_vkMapMemory vkMapMemory;
	extern PFN_vkQueueSubmit vkQueueSubmit;
	extern PFN_vkResetCommandBuffer vkResetCommandBuffer;
	extern PFN_vkResetDescriptorPool vkResetDescriptorPool;
	extern PFN_vkResetEvent vkResetEvent;
	extern PFN_vkResetFences vkResetFences;
	extern PFN_vkSetEvent vkSetEvent;
	extern PFN_vkUnmapMemory vkUnmapMemory;
	extern PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
	extern PFN_vkWaitForFences vkWaitForFences;
}

#endif // __ANDROID__
